// editor_profiler — thin C helper around the motor's `profiler` map. We can't
// safely call the motor's `profile()` / `profile_setstat()` macros from C++
// (the macros depend on the anonymous-struct type generated by `map(K,V)`
// which doesn't survive a C++ translation unit), so we expose three minimal
// C functions: record a timing, snapshot the current entries, reset counters.
//
// All three are no-ops when ENABLE_PROFILER is 0 or `profiler_enabled == 0`,
// so the C++ side can call them unconditionally.
//
// The Panel side (panels/profiler_panel.cpp) uses these via a tiny C++ RAII
// wrapper (ProfileScope) — see `core/profile_scope.h`.

#include <math.h>     // NAN, isnan
#include <string.h>   // strdup
#include "engine.h"
#include "components_api.h"

// ---- record one timing sample (microseconds) -------------------------------
// Matches the motor's `profile()` macro semantics: store the raw cost, then
// blend into the exponential-moving-average (factor 0.25 / 0.75 — same as
// game_profiler.h:18). The map allocates one entry per unique `name` key.
//
// CRITICAL: the map keys are NOT copied internally — we must hand it a stable
// string. We use `strdup` on first insertion; the map owns the heap copy for
// its lifetime (one allocation per unique editor-section). The motor's own
// profile() macro avoids this by using FILELINE which expands to a static
// string literal, so this helper is the only place where we strdup.
API void editor_profile_record_us(const char* name, double us) {
    if (!profiler_enabled || !profiler || !name) return;
    // Probe with the literal pointer first — if already present, reuse it
    // (no allocation). map_find takes a void* key and runs `cmp` (less_str)
    // on it, so a const-literal lookup works against any equivalent string.
    struct profile_t* found = map_find(profiler, (char*)name);
    if (!found) {
        char* keycopy = strdup(name);
        struct profile_t initial = { NAN, 0, 0 };  // NaN stat => timer entry
        found = map_find_or_add_allocated_key(profiler, keycopy, initial);
    }
    if (found) {
        int32_t cost = (int32_t)us;
        found->cost = cost;
        // EMA blend (matches motor): avg = cost*0.25 + avg*0.75
        found->avg = (int32_t)(cost * 0.25 + (double)found->avg * 0.75);
    }
}

// ---- snapshot the current profiler table -----------------------------------
// Caller-allocates `out` for up to `max_count` entries; returns the actual
// number filled. Use editor_profiler_count() first to size the array.
//
// The motor stores avg in microseconds — we convert to milliseconds here so
// the panel side doesn't have to.

API int editor_profiler_count(void) {
    if (!profiler_enabled || !profiler) return 0;
    return (int)map_count(profiler);
}

API int editor_profiler_collect(editor_profile_entry_t* out, int max_count) {
    if (!profiler_enabled || !profiler || !out || max_count <= 0) return 0;
    int n = 0;
    for each_map_ptr(profiler, const char *, key, struct profile_t, val) {
        if (n >= max_count) break;
        out[n].name     = *key;
        out[n].avg_ms   = (float)val->avg / 1000.0f;
        out[n].stat     = val->stat;
        out[n].is_timer = isnan(val->stat) ? 1 : 0;
        n++;
    }
    return n;
}

// Set a counter value (mirrors the motor's `profile_setstat` macro). Used by
// the editor render-walk to publish per-frame stats like MeshCount /
// UniqueModels. The map entry is created on first use with stat=0 (so it
// shows as a counter, not a timer).
API void editor_profile_set_counter(const char* name, double value) {
    if (!profiler_enabled || !profiler || !name) return;
    struct profile_t* found = map_find(profiler, (char*)name);
    if (!found) {
        char* keycopy = strdup(name);
        struct profile_t initial = { 0.0, 0, 0 };  // stat=0 (not NaN) => counter
        found = map_find_or_add_allocated_key(profiler, keycopy, initial);
    }
    if (found) {
        found->stat = value;
    }
}

// Reset only the counter entries (profile_incstat / setstat). Timer averages
// are kept rolling (the EMA naturally decays on its own). Matches the
// motor's `ui_profiler` end-of-frame reset behavior.
API void editor_profiler_reset_counters(void) {
    if (!profiler_enabled || !profiler) return;
    for each_map_ptr(profiler, const char *, key, struct profile_t, val) {
        (void)key;
        if (!isnan(val->stat)) val->stat = 0;
    }
}

// Hard reset — drops every entry. Useful when the user wants to start a
// fresh measurement window (e.g. after enabling a new feature). We free the
// `strdup`'d keys we own; the motor's own entries (FILELINE-string-literal
// keys) are not freed — that's safe because the map_free macro frees the
// value-pair structs but leaves the static key strings alone.
API void editor_profiler_clear(void) {
    if (!profiler_enabled || !profiler) return;
    map_clear(profiler);
}
