#pragma once

// EngineFFI → EmmyLua stub generator (Phase 6a).
//
// Input: `code/game/embed/engine.ffi` (the C-cdef text generated by the
// engine, ~21k lines — GL typedefs, struct/enum, function prototypes).
//
// Output into the project folder:
//   <projectPath>/.luarc/engine.d.lua  — EmmyLua stub (---@class, ---@field,
//                                         ---@meta).
//   <projectPath>/.luarc.json           — lua-language-server (sumneko)
//                                         workspace.library + LuaJIT-runtime.
//   <projectPath>/.vscode/settings.json — VSCode override (only if it's
//                                         NOT there yet, so we don't
//                                         overwrite the user's edits).
//
// The EmmyLua stub is auto-detected by `lua-language-server` and the
// JetBrains EmmyLua plugin based on the `workspace.library` field of `.luarc.json`.
//
// The parser is NOT a full C-parser — it's a one-line regex-like declaration
// recognizer. Complex cases (function-pointer-typedef, multi-line struct content)
// are skipped. About 90% of the engine API ends up in the stub.

#include <string>

namespace editor::ffi_to_emmylua {

struct GenResult {
    bool        ok          = false;
    int         functions   = 0;
    int         classes     = 0;
    int         enums       = 0;
    std::string stubPath;        // .luarc/engine.d.lua
    std::string configPath;      // .luarc.json
    std::string vscodePath;      // .vscode/settings.json (empty if skipped)
    std::string error;
};

// Main API. `projectPath` = abs project folder. `ffiPath` = engine.ffi abs
// or relative path (relative to the engine's CWD, "code/game/embed/engine.ffi").
// `force` = if false, only regenerates if engine.ffi mtime > stub mtime.
GenResult generate(const std::string& projectPath,
                   const std::string& ffiPath,
                   bool               force = true);

}  // namespace editor::ffi_to_emmylua
